// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuB16RY0pt7iSxXXODMPiOxZ3-HPHHhP8',
    appId: '1:21201203842:web:7b315a5652f47167f0fa9b',
    messagingSenderId: '21201203842',
    projectId: 'smartclimate-c3631',
    authDomain: 'smartclimate-c3631.firebaseapp.com',
    storageBucket: 'smartclimate-c3631.firebasestorage.app',
    measurementId: 'G-0CYXYJP6CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnFiOB5SM0dNZcQ8lk3bzagxymZH1SJKo',
    appId: '1:21201203842:android:c66fef6c3662966cf0fa9b',
    messagingSenderId: '21201203842',
    projectId: 'smartclimate-c3631',
    storageBucket: 'smartclimate-c3631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGY6bY6qZmp8WzrpxqV4v2pIqRI9Xioi0',
    appId: '1:21201203842:ios:1b032478e4c261edf0fa9b',
    messagingSenderId: '21201203842',
    projectId: 'smartclimate-c3631',
    storageBucket: 'smartclimate-c3631.firebasestorage.app',
    iosClientId: '21201203842-ut69u9jgca1hdrb4rugv21up27jrmdc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartclimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGY6bY6qZmp8WzrpxqV4v2pIqRI9Xioi0',
    appId: '1:21201203842:ios:1b032478e4c261edf0fa9b',
    messagingSenderId: '21201203842',
    projectId: 'smartclimate-c3631',
    storageBucket: 'smartclimate-c3631.firebasestorage.app',
    iosClientId: '21201203842-ut69u9jgca1hdrb4rugv21up27jrmdc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartclimate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuB16RY0pt7iSxXXODMPiOxZ3-HPHHhP8',
    appId: '1:21201203842:web:9bcd8e2fde61deb1f0fa9b',
    messagingSenderId: '21201203842',
    projectId: 'smartclimate-c3631',
    authDomain: 'smartclimate-c3631.firebaseapp.com',
    storageBucket: 'smartclimate-c3631.firebasestorage.app',
    measurementId: 'G-VB6CHF1VBC',
  );

}